name: "pokemon_pipeline"
version: "1.0.0"
config-version: 2

profile: "pokemon_profile"

model-paths: ["models"]
test-paths: ["tests"] # dq assertions
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  pokemon_pipeline:
    staging:
      +materialized: view # Default staging is views (Silver)
      stg_pokemon_unified:
        +materialized: table # Consolidated target staging is a physical table
